import React from 'react';

function OAuthLogin() {
  const handleLogin = () => {
    // Redirect to the OAuth2 authorization endpoint.
    // This URL is generated by Spring Security. Typically, for Google it is:
    window.location.href = 'http://localhost:8081/oauth2/authorization/google';
  };

  return (
    <div>
      <h2>Login with Google</h2>
      <button onClick={handleLogin}>Login with Google</button>
    </div>
  );
}

export default OAuthLogin;
